# Generated by Django 5.0.2 on 2024-03-14 15:59

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_phone_number_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='user',
            name='oname',
            field=models.CharField(verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegramid',
            field=models.CharField(blank=True, null=True, verbose_name='id телеграмм пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text="Номер телефона должен быть введен в формате: '+7495200000'. Допускается до 11 цифр.", max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
